### ISSUE TITLE
Parameter name: _gitVersion - value cannot be null

### ISSUE THREAD

**Issue by wangfeng19890** [Microsoft/azure-pipelines-agent#1627]
VSTS

Agent:
On premises
Windows Server 2012 R2
Agent: 2.123.0
VS Enterprise 15.5

## What's not working?
Get Sources Task (from VSTS Git)

Sometimes when new builds are queued an error is generated during get sources phase
Retry normally fixes this.

The main issue is with scheduled builds, if these run overnight and nobody is around and we get this error then the builds fails.

The source option is VSTS Git and there are no source/git related variables set on the definition (like custom path to git etc...)

## Agent and Worker's Diagnostic Logs
2018-05-23T07:35:59.1679627Z ##[section]Starting: Get Sources
2018-05-23T07:35:59.2089296Z Syncing repository: ****** (TfsGit)
2018-05-23T07:35:59.2163327Z Prepending Path environment variable with directory containing 'git.exe'.
2018-05-23T07:35:59.2248352Z ##[command]git version
2018-05-23T07:35:59.2958375Z
2018-05-23T07:35:59.3431548Z ##[error]Value cannot be null.
Parameter name: _gitVersion
2018-05-23T07:35:59.3521760Z ##[section]Finishing: Get Sources

**Comment by TingluoHuang** [comment]
@wangfeng19890 have you try latest version agent? you are using 2.123.0, the latest version is 2.134.2

**Comment by TingluoHuang** [comment]
@wangfeng19890 i am 99% sure we fixed a bug that will cause the behavior you saw.

**Comment by wangfeng19890** [comment]
@TingluoHuang  I am very sorry to tell you that this bug is still happening even thought we already update the agent to latest version 2.134.2. Actually, we scheduled a build to run every morning, and this error happened many times.

**Comment by TingluoHuang** [comment]
@wangfeng19890 can you run `<youragentroot>\externals\git\cmd\git version` from your agent machine and see what you get?

**Comment by wangfeng19890** [comment]
@TingluoHuang  Yes, just now I run this command and get **git version 2.14.1.windows.1** So, is it correct? What should we get?

**Comment by TingluoHuang** [comment]
@wangfeng19890  that is expected. Do you have access to your build machine? can you share your agent diag log with me?
the log is under `<youragentroot>\_diag`, you can zip the entire folder and send to `tihuang @ microsoft .com`

**Comment by TingluoHuang** [comment]
@wangfeng19890 also, how frequently are hitting this issue? it would be great if you have consistent repro.

**Comment by duaneking** [comment]
Confirmed as still an issue.  Our entire team is blocked by this atm.

**Comment by TingluoHuang** [comment]
make sure you don't have something like https://www.avecto.com/defendpoint that monitor the agent folder, that software might affect dotnet launch process.

**Comment by TingluoHuang** [comment]
can't repro, close for now, please reopen if more help is needed.
