### ISSUE TITLE
Initialize Job: ##[error]One or more errors occurred. (One or more errors occurred. (Invalid File or Directory attributes value. (Parameter 'Attributes'))) (Invalid File or Directory attributes value. (Parameter 'Attributes'))

### ISSUE THREAD

**Issue by emul8ed** [microsoft/azure-pipelines-agent#3307]
## Having issue with YAML?
No

## Having issue with Tasks?
Maybe?

## Having issue with software on Hosted Agent?
No

## Having generic issue with Azure-Pipelines/VSTS/TFS?
No

## Have you tried troubleshooting?
No

## Agent Version and Platform
2.182.1/aarch64

OS of the machine running the agent? OSX/Windows/Linux/...
Ubuntu 18.04

## Azure DevOps Type and Version
dev.azure.com

If dev.azure.com, what is your organization name? https://dev.azure.com/{organization} or https://{organization}.visualstudio.com
sqlsapphire

## What's not working?

I'm getting the following error in the "Initialize Job" phase:

##[error]One or more errors occurred. (One or more errors occurred. (Invalid File or Directory attributes value. (Parameter 'Attributes'))) (Invalid File or Directory attributes value. (Parameter 'Attributes'))

The issue appears to be triggered by the appearance of a zero-byte file with an invalid name being dropped in the root of the source directory. This trips up the recursive delete in "initialize job". Once this file appears, "initialize job" will consistently fail until I manually log into the agent and delete it. Unfortunately I didn't note the file name the last time the issue arose, but when it happens again I will note it in a comment. I've not yet observed a discernible pattern for when this file appears and with which builds, which leads me to believe it may be an agent bug rather than a task bug. I've not seen this with similarly-configured x86_64 agents, so I believe it's specific to aarch64.

## Agent and Worker's Diagnostic Logs

[Agent_20210301-202018-utc.log](https://github.com/microsoft/azure-pipelines-agent/files/6092292/Agent_20210301-202018-utc.log)
[Agent_20210301-202056-utc.log](https://github.com/microsoft/azure-pipelines-agent/files/6092293/Agent_20210301-202056-utc.log)
[Worker_20210305-142705-utc.log](https://github.com/microsoft/azure-pipelines-agent/files/6092295/Worker_20210305-142705-utc.log)

**Comment by emul8ed** [comment]
Happened again. Here's the problem file:

```
$ find . -type f | grep -a 70@@
./w01/1/s/70@@�@8

$ ls -alrt ./w01/1/s/
...
-rw-r--r--  1 vsts vsts    0 Mar  5 15:04 ''$'\001''70@@'$'\230\025\001''@8'
...
```

**Comment by anatolybolshakov** [comment]
Hi @emul8ed has this file been created by your pipeline? Have you seen similar issues on other aarch64 environments?

**Comment by anatolybolshakov** [comment]
Hi @emul8ed is this issue still actual for you?

**Comment by anatolybolshakov** [comment]
Hi @emul8ed I'm closing this due to inactivity at the moment, it's still not reproducible for us - please let us know if you still have this issue

**Comment by emul8ed** [comment]
Yes, I still have this issue. I have to manually rm -f $(Build.SourcesDirectory)/* at the end of every build to work around it. Please reactivate.

**Comment by emul8ed** [comment]
> Hi @emul8ed has this file been created by your pipeline?

No. We run the same pipeline steps on x86_64 agents without any issues.

> Have you seen similar issues on other aarch64 environments?

No, I have only ever seen this with an aarch64 Azure DevOps agent.

**Comment by junyuan-z** [comment]
We are having this same issue too.

**Comment by anatolybolshakov** [comment]
@emul8ed @junyuan-z could you please provide some repro steps for this - to check it on our side?

**Comment by d3r3kk** [comment]
We use docker containers for our agents, and I've created an image with the issue present. Let me know if you would like to discuss @anatolybolshakov - I can give you access to our running agents in a call or I can provide the problematic container for you and your team to inspect.

**Comment by emul8ed** [comment]
@d3r3kk, do you have component governance detection enabled on your aarch64 agents? Does it fail with "Unable to locate dotnetcore on build agent"? Once I started disabling component governance detection on the aarch64 agents, the issue seemed to disappear. It came back today and, sure enough, I discovered I'd forgotten to disable CG for a build I added a couple of days ago.

**Comment by d3r3kk** [comment]
Ooh that's a great tip, thanks I'll try that.

**Comment by d3r3kk** [comment]
### @d3r3kk's extra-bad bandaid to workaround invalid file names on Azure DevOps Agents™️

Seems I wasn't successful in shutting down component governance with my change yesterday. Will have to investigate further. For now, I've written a bit of a bandaid to clean up my docker containers running on an ARM64 host:


```bash
DO_DELETE=' '
for i in $(sudo docker container ls --format '{{.Names}}')
do
  echo $i
  sudo docker exec -t $i /bin/find /path-to-agent/_work -maxdepth 3 -type f -iname '*@8'
done
```
...and then once you run that command and it shows you exactly the hosts that have the offending file, you can set `DO_DELETE='-delete'` to actually perform the delete action in `find`.

Note: `-maxdepth` should be set to the lowest number of folders to traverse under `.../agent/_work` to find that offending file, this speeds the command up a ton. Mine are found in the root of all git sources, so `/home/agent/_work/s/repo-name/`, or 2 underneath the `.../agent/_work` folder (and then I put it to 3 to just be extra sure).

**Comment by DenisRumyantsev** [comment]
As I can see from provided logs, the error occurs in the `src/Agent.Sdk/Util/IOUtil.cs` file in [this line](https://github.com/microsoft/azure-pipelines-agent/blob/e25038c60732f8191de7b852f1759e094bd3cff2/src/Agent.Sdk/Util/IOUtil.cs#L461):
```cs
item.Attributes = item.Attributes & ~FileAttributes.ReadOnly;
```
[Here](https://docs.microsoft.com/en-us/dotnet/api/system.io.fileattributes?view=net-5.0#fields) is the documentation about the `ReadOnly` attribute, which changes from `true` to `false` during the line execution.
Perhaps, something goes wrong when trying to change the file status.

**Comment by DenisRumyantsev** [comment]
It is possible that the issue is related to encoding and has already been fixed in higher versions of dotnet, but I did not find similar issues in [the related repository](https://github.com/dotnet/runtime/issues).

**Comment by DenisRumyantsev** [comment]
@d3r3kk, could you please run a pipeline agent build with the 3.1.15 dotnet runtime version and check if the error has disappeared? I have provided it via email.

**Comment by d3r3kk** [comment]
The error remains 😥 I've sent along new results with the 3.1.15 agent via email.

**Comment by DenisRumyantsev** [comment]
Created a related issue in the dotnet/runtime repo

**Comment by DenisRumyantsev** [comment]
Since the exception message was improved we will be able to get more information about this issue when changes are deployed

**Comment by AhmedBM** [comment]
im also experiancing this issue, filed a bug https://github.com/microsoft/azure-pipelines-agent/issues/3457

**Comment by DenisRumyantsev** [comment]
@d3r3kk could you please update your pipeline agent to the `2.194.0` version (currently latest)
and provide **[worker diagnostic logs](https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops#worker-diagnostic-logs)** when this error happens again?

**Comment by DenisRumyantsev** [comment]
@AhmedBM could you please provide us with **[worker diagnostic logs](https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops#worker-diagnostic-logs)**?
Please update your pipeline agent to the `2.194.0` version (or higher) first.

**Comment by DenisRumyantsev** [comment]
@d3r3kk, @AhmedBM,
I'm closing this issue due to a lack of information for the investigation. Feel free to request reopening this once there will be new information about this issue.

**Comment by Borda** [comment]
seem we are facing a similar issue with Pipeline start/init so even before the first step would be executed... https://dev.azure.com/Lightning-AI/compatibility/_build/results?buildId=156277&view=logs&j=cb44143e-1b72-550b-97cf-26ffc4f8d032&t=23281d13-276e-4b9b-9482-bb7f15b8d4de
