### ISSUE TITLE
First bash task in job intermittently failing with node ENOENT error

### ISSUE THREAD

**Issue by corppeon** [microsoft/azure-pipelines-agent#3400]
We've been seeing an issue for the last week or so, intermittently getting an error, looks to be the first task in Linux jobs running on our dev.azure.com pipelines with our self-hosted Azure agents. Tried updating to latest agent version 2.186.1, but issue still present.
We're specifying tasks to run inside a Docker container.

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn /__a/externals/node10/bin/node ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
    at onErrorNT (internal/child_process.js:376:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

##[debug]Microsoft.VisualStudio.Services.Agent.Util.ProcessExitCodeException: Exit code 1 returned from process: file name '/usr/bin/docker', arguments 'exec -i -u 1000 13f0677475ead4feb4c53652052337f0a0160eb4813f9c97562b6b2ab6c02bab /__a/externals/node/bin/node /__w/_temp/containerHandlerInvoker.js'.
   at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.ContainerStepHost.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Boolean inheritConsoleHandler, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.NodeHandler.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)

Azure Agent VMs are running CentOS 7.4 as the host OS with the container running CentOS 7.8.

**Comment by anatolybolshakov** [comment]
Hi @corppeon this is a known issue happened because of breaking change introduced by docker - we already merged related [PR](https://github.com/microsoft/azure-pipelines-agent/pull/3392) and it will come with the next agent release.
Since this issue happens with containers which have a root working directory being set up - as a workaround you can try to use modified container with current working directory specified as home directory of current user.

**Comment by corppeon** [comment]
We've just updated to v2.187.2, and we're still seeing the problem intermittently as before...

2021-06-02T16:50:00.2581853Z Task         : Bash
2021-06-02T16:50:00.2582161Z Description  : Run a Bash script on macOS, Linux, or Windows
2021-06-02T16:50:00.2582633Z Version      : 3.182.0
2021-06-02T16:50:00.2583789Z Author       : Microsoft Corporation
2021-06-02T16:50:00.2584158Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
2021-06-02T16:50:00.2584547Z ==============================================================================
2021-06-02T16:50:00.4570831Z events.js:160
2021-06-02T16:50:00.4571844Z       throw er; // Unhandled 'error' event
2021-06-02T16:50:00.4572552Z       ^
2021-06-02T16:50:00.4572749Z 
2021-06-02T16:50:00.4573250Z Error: spawn /__a/externals/node10/bin/node ENOENT
2021-06-02T16:50:00.4573891Z     at exports._errnoException (util.js:1020:11)
2021-06-02T16:50:00.4574574Z     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
2021-06-02T16:50:00.4575457Z     at onErrorNT (internal/child_process.js:376:16)
2021-06-02T16:50:00.4576173Z     at _combinedTickCallback (internal/process/next_tick.js:80:11)
2021-06-02T16:50:00.4576963Z     at process._tickCallback (internal/process/next_tick.js:104:9)
2021-06-02T16:50:00.4887079Z ##[error]Exit code 1 returned from process: file name '/usr/bin/docker', arguments 'exec -i -u 1000  -w /home/azureuser_azpcontainer 4b2c44afa49be8e0c99e3040aad47a4b8fc68f5ed42a5e47f84c3e65f4b42717 /__a/externals/node/bin/node /__w/_temp/containerHandlerInvoker.js'.

**Comment by anatolybolshakov** [comment]
@corppeon could you please share docker image you use - to reproduce this?

**Comment by anatolybolshakov** [comment]
@corppeon could you please share full pipeline log containing this error? You can send this also to my email - v-anbols@microsoft.com

**Comment by anatolybolshakov** [comment]
Hi @corppeon per offline discussion - do you have any updates about trying of 2.185.1 agent version?
To disable auto-upgrade - you also need to disable agent auto-upgrade for relevant agent pool – to avoid immediate auto-upgrade.

**Comment by corppeon** [comment]
Hi,

We think we’ve just fixed the issue - we are pulling multiple git repos, and we’re now explicitly setting the path settings for each checkout step. This seems to have fixed the reported intermittent ENOENT exception.

Many thanks for your help and following up.

**Comment by anatolybolshakov** [comment]
@corppeon got it thanks! I'm closing this since it's resolved, feel free to ask any other questions.

**Comment by mtene** [comment]
Hi @anatolybolshakov we are now experiencing what looks like a related issue:

```
- checkout: main_repo
  path: s

- checkout: extension_repo # actually, self (see below)
  path: s/src/.../subdir
```

Our self-hosted agents intermittently throw this error on the second checkout:
```
##[error]Unable to process command '##vso[plugininternal.updaterepositorypath alias=self;]/datadrive/vsts/agent/_work/117/s/src/../subdir' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)
##[error]Repository path '/datadrive/vsts/agent/_work/117/s/src/../subdir' should be located under agent's work directory '/__w/117'.
Repository is current at '/datadrive/vsts/agent/_work/117/s/extension_repo', move to '/datadrive/vsts/agent/_work/117/s/src/.../subdir'.
##[warning]Unable move and reuse existing repository to required location.
Repository will be located at '/datadrive/vsts/agent/_work/117/s/src/../subdir'.
```

The full checkout that follows is successful, but the error stops the pipeline from continuing.
If the same agents is re-queued then, the problem goes away. It will reappear maybe 1-2 weeks later, probably after the agent undergoes maintenance.

It might be relevant that extension_repo is a git submodule of main_repo, located exactly at the path where the checkout happens. The reason we are doing it this way is because this is a CI pipeline for extension_repo, so we need to checkout the version of extension_repo corresponding to the PR being tested. The code under extension_repo is an optional plugin to main_repo, so it can not be tested in isolation.

Any thoughts?

**Comment by mtene** [comment]
I have opened #3520 on this
