### ISSUE TITLE
Failed to install agent on SUSE Linux Enterprise Server 12 SP4

### ISSUE THREAD

**Issue by crushonme** [microsoft/azure-pipelines-agent#3508]
## Agent Version and Platform
Version of your agent? 

**2.187.2, also test in latest version.**

OS of the machine running the agent?  **Linux, SUSE Linux Enterprise Server 12 SP4**

## Azure DevOps Type and Version
dev.azure.com (formerly visualstudio.com) or on-premises TFS/Azure DevOps Server?
**On-Premises**
If on-premises, which release? **2020 update 1**

## What's not working?
1. Cannot detect SUSE Linux Enterprise Server 12 SP4;
2. After manually add LIKE_ID in /etc/os-release, we will get below error
![image](https://user-images.githubusercontent.com/3364366/129913051-25db747d-3eaf-4ab1-807c-cb2843f9902f.png)

**Comment by anatolybolshakov** [comment]
HI @crushonme this issue should be already fixed in upcoming agent 2.191.1 version - we will let you know once it's available.

**Comment by MsNewbie** [comment]
Hello Team,

Verified this release(2.191.1) and confirmed that the issue is still not fixed.

![image](https://user-images.githubusercontent.com/5129908/132474713-49798c04-7ab8-4d67-b4c4-a681c3d0ccfd.png)

![image](https://user-images.githubusercontent.com/5129908/132474743-e9cb733a-9a64-4e6c-aa07-9432ddb10ea9.png)

**Comment by anatolybolshakov** [comment]
Hi @Johnny-spec thanks for reporting! Could you please try to adjust installdependencies.sh script like below and run it again?
![image](https://user-images.githubusercontent.com/8779682/132541942-364b213b-a271-4eb6-bb62-f1b02986be19.png)

**Comment by Johnny-spec** [comment]
@anatolybolshakov There are errors after adjust the script, it seems like that my test environment doesn't have valid official repo of SLES.

![image](https://user-images.githubusercontent.com/5129908/132633030-0748d123-7a09-42dd-8303-c03cb7fc2604.png)

So I manually installed the 2 libraries with RPM package, but still get below errors:

![image](https://user-images.githubusercontent.com/5129908/132633316-f9b2dca2-03bd-4d53-818c-5cbb2bef2594.png)

**Comment by anatolybolshakov** [comment]
@Johnny-spec have you tried deinstallation of libzl?

**Comment by Johnny-spec** [comment]
> @Johnny-spec have you tried deinstallation of libzl?
I tried to remove the libzl, after that the whole system is not work now.
![image](https://user-images.githubusercontent.com/5129908/133361798-0fcfc18d-d4a3-462d-9fd4-97319f2c95af.png)

**Comment by WALLOUD** [comment]
S
Drug dropped
