### ISSUE TITLE
Agent disconnecting on OSX 12.2 sporadically and never recovering.

### ISSUE THREAD

**Issue by Keki91** [microsoft/azure-pipelines-agent#3737]
## Agent Version and Platform
Version of your agent? 2.198.2 / 2.198.3

OS of the machine running the agent? OSX 12.2

## Azure DevOps Type and Version
https://dev.azure.com/lister-app

## What's not working?

_Throws Agent connect error: The http request timed out after 00:01:00.. Retrying until connected._

It rarely seems to successfully reconnect. I didn't have this issue with 2.196.2 on the same machine a few weeks ago, this has only been happening since upgrading to 2.198.2 (may be a coincidence) - but it always shows as Online within the agent list on https://dev.azure.com 

## Agent and Worker's Diagnostic Logs
Logs are located in the agent's `_diag` folder. The agent logs are prefixed with `Agent_` and the worker logs are prefixed with `Worker_`. All sensitive information should already be masked out, but please double-check before pasting here.

Agent Logs: https://gist.github.com/Keki91/1a0ad9663e347b806cb70ef7a8f599fb

There doesn't seem to be anything in the worker logs relating to this.

**Comment by denis-tikhomirov** [comment]
@Keki91, do you have agent based on other OS (Windows or Linux)? Do they have the same issue in case they use the same network for connection?
Do you use IPv4, IPv6 or both the protocols in network connection on agent/host of agent? If both the protocols are available for using, please make sure that ADO is available in case of using each of them.

**Comment by Keki91** [comment]
@denis-tikhomirov.

Also have an agent running Windows 10, this doesn't have the same issues. It's running under IPv4. ISP doesn't support IPv6.

**Comment by denis-tikhomirov** [comment]
It looks like the issue should be solved by this PR https://github.com/microsoft/azure-pipelines-agent/pull/3738.
And the fix is included to release 2.200.0 https://github.com/microsoft/azure-pipelines-agent/releases/tag/v2.200.0.

**Comment by denis-tikhomirov** [comment]
@Keki91, the issue should be resolved now with new version of pipeline agent (2.200.0). Please check that the issue is solved for you.

**Comment by Keki91** [comment]
Updated the agents today and will let you know if they're still having an issue.

**Comment by Keki91** [comment]
Seems to still be an issue in MacOS on 2.200.0.

**Comment by anatolybolshakov** [comment]
Hi @Keki91 the error above indicates that there are some issues with connection to server. Were there any changes in your environment?
Have you tried to run it with 2.196.2 now (you can disable automate agent upgrade in the pool settings)?

**Comment by Keki91** [comment]
Hi, @anatolybolshakov 

Tried it on each version which has released up to now (currently 2.200.2) and it still seems to suffer the same issue. 

It could be something environmental, however, I have a Windows build on the same network which is not suffering this issue.

**Comment by anatolybolshakov** [comment]
@Keki91 yes, seems that there was some environmental change not related to the agent itself... Please note that there was some [change](https://devblogs.microsoft.com/visualstudio/azure-devops-requires-tls-1-2-on-all-connections-including-visual-studio/) regarding TLS 1.0/1.1 deprecation.
I would suggest to open a ticket on https://developercommunity.visualstudio.com/search?space=21 to double-check it.
