### ISSUE TITLE
v2.217.x breaks --once argument when running the agent in Docker/k8s

### ISSUE THREAD

**Issue by neoswallow** [microsoft/azure-pipelines-agent#4142]
Following method all fails with running the agent in Docker.

```
docker run dockeragent:latest --once
```

```
    command: "--once"
```
in docker-compose.yaml

```
          args:
            - '--once'
```
in k8s deployment

Error message from Docker:
```
./env.sh: line 44: --once: invalid variable name
```

Error message from k8s pod:
```
./env.sh: line 44: --once: bad substitution
```

This worked fine up until v2.214.1 and then it's broken with v2.217.0.
Since docker image run always download latest version, all our agents in Docker are broken.

Docker image was built using instructions on this page: https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops#linux

**Comment by Frettarix** [comment]
We're experiencing this exact same issue. As of a newer version of the image (most likely v2.217.0 as being reported) the .env file is trying to add any argument as a variable. '--once' is not recognized as a valid argument due to the naming conventions allowed in linux argument names I reckon.

`for arg in "$@"
do
    if [[ ! " ${varCheckList[@]} " =~ " ${arg} " ]]; then
        varCheckList+=($arg)
    fi
done`

This is impacting all of our agents on multiple hosts.

**Comment by Rokschoon1** [comment]
We are going to try and rollback to 214 version by bypassing the '_apis/distributedtask/packages/agent' which is automatically selecting the 2.17 version. But please fix this soon. We can imagine this is impacting a lot of people/teams.

**Comment by Frettarix** [comment]
We've implemented a similar fix. We downloaded v2.214.1 and tested this agent locally. This one seems to work so we've hardcoded this one into our 'start.sh' for now as well, commenting out the old latest URL.

This seems to work for now but we're hoping that this gets fixed soon.

A side question: Does anyone know whether this is being tested before release?

**Comment by KonstantinTyukalov** [comment]
Thank you for reporting, we're on process on investigation the issue, will get back soon

**Comment by mmisztal1980** [comment]
We've detected this circa 3pm CET on Feb 1st 2023. Issue still persists, we've notified support. 

Both `--once` and `--unattended` params are taken into account by `source ./env.sh` (which is invoked both in `start.sh` and in `config.sh`)

**Comment by neoswallow** [comment]
I would have to guess that somehow version release tied to an account.
I did take a look at v2.217.2 when it was released which removed the new code.
However, this repo is saying the latest release is still @v2.214.1.
And REST API with our account still shows v2.217.0 as the latest version.
Is there a way for our account to get v2.217.2 as the latest version?

**Comment by neoswallow** [comment]
I would have to guess that somehow version release tied to an account.
I did take a look at v2.217.2 when it was released which removed the new code.
However, this repo is saying the latest release is still @v2.214.1.
And REST API with our account still shows v2.217.0 as the latest version.
Is there a way for our account to get v2.217.2 as the latest version?

**Comment by KonstantinTyukalov** [comment]
@neoswallow if you use self-hosted agent, you can download the latest version directly from the release page [here](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v2.217.2)

For MS-hosted agents: We are in process of rolling out 2.217.2 to all customers, for now your agent version should be 2.214.1 or 2.217.2 depending on release status.

>And REST API with our account still shows v2.217.0 as the latest version.

Could you please re-check? If it still 2.217.0, could you try running a test pipeline to see if the REST API shows the truth?

Thanks

**Comment by neoswallow** [comment]
@KonstantinTyukalov I do use self-hosted but this issue is only on Docker image run which downloads new and latest agent on every run.
Hence the reason to supply `--once`.

So I was still getting 2.217.0 on the weekend from REST API.

**Comment by neoswallow** [comment]
Anyway, I'll revert the change back to latest version, test again and report back.

**Comment by neoswallow** [comment]
I can confirm that 2.217.2 fixes the issue and is working well on docker and k8s.
I'll close the issue.
