### ISSUE TITLE
[BUG]: Agent Resource Metrics Redirection Issue

### ISSUE THREAD

**Issue by mjesperson** [microsoft/azure-pipelines-agent#4469]
### What happened?

The recent addition of agent resource metrics makes monitoring log output almost impossible with system.debug enabled. The page while watching the logs constantly switches to the resource metrics. 

If we click back on the task to look at the logs it keeps bringing me to the metrics. Can we add a way to disable this? Or use a different flag than system.debug? It makes monitoring out pipeline runs impossible and we value the extra output from system.debug but don't want to continually be redirected to these metrics every few seconds that it updates.

### Versions

3.771.1

Both Ubuntu in Docker and Windows

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [X] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu 20.04 / Windows Server 2019

### Relevant log output

```shell
##[debug]Agent running environment resource - Disk: available:12911852.00MB out of 14532478.00MB, Memory: used 88MB out of 515552MB, CPU: usage 3.99
##[debug]Agent running environment resource - Disk: available:12911845.00MB out of 14532478.00MB, Memory: used 88MB out of 515552MB, CPU: usage 3.93
##[debug]Agent running environment resource - Disk: available:12911831.00MB out of 14532478.00MB, Memory: used 88MB out of 515552MB, CPU: usage 3.81
##[debug]Agent running environment resource - Disk: available:12911823.00MB out of 14532478.00MB, Memory: used 88MB out of 515552MB, CPU: usage 3.70
##[debug]Agent running environment resource - Disk: available:12911813.00MB out of 14532478.00MB, Memory: used 88MB out of 515552MB, CPU: usage 3.63
```

**Comment by kirill-ivlev** [comment]
Hi @mjesperson ,
Thank you for reporting this issue, we will take a look.

**Comment by HarshdeepGupta** [comment]
Encountering the same issue, is there any ETA on this getting resolved?

**Comment by soniaAr** [comment]
Hello,
i have the same issue, cannot even check the logs (running stryker mutator testing)

**Comment by serbathome** [comment]
> Hi @mjesperson , Thank you for reporting this issue, we will take a look.

Any chance it will be fixed soon?

**Comment by kirill-ivlev** [comment]
Hi @serbathome,
Thank you for raising this, fix was merged and soon will be rolled out.

**Comment by misseill** [comment]
Is this still awaiting deployment?

**Comment by kirill-ivlev** [comment]
@misseill latest agent was rolled out, could you please confirm that issue is resolved for you?

**Comment by kirill-ivlev** [comment]
Thank you for your feedback, since we haven't received any updates, I closing this item.
Please feel free to post updates if you still facing this issue.

**Comment by pbcahill** [comment]
Hi @kirill-ivlev, why was this closed, could you please reopen? This bug still exists and nothing has been merged/deployed to fix it. I think this is the PR to fix it, but no idea if it works - https://github.com/microsoft/azure-pipelines-agent/pull/4486

Monitoring running pipeline logs is still a very poor experience with this resource metrics feature/bug.

**Comment by MHebes** [comment]
I'm not sure which version exactly this was fixed in, but I updated my agent from 3.230.0 to 3.234.0 and it fixed the issue.

**Comment by RobLSDev** [comment]
> I'm not sure which version exactly this was fixed in, but I updated my agent from 3.230.0 to 3.234.0 and it fixed the issue.
> 
> Before, my output would switch between showing exclusively `Agent environment resources` lines and my logs.
> 
> After, those `Agent environment resources` lines are correctly interleaved with my logs.

That wasn't the issue stated for this bug.  The problem listed above is that those statements are flooding the logs, making them useless for other purposes.

**Comment by Marin73** [comment]
Why is this bug closed? It is an incredibly annoying spam of messages that are completely meaningless.

![image](https://github.com/microsoft/azure-pipelines-agent/assets/99972229/87443d67-e6e0-499d-ac8b-ce984f067581)

It clogs up the log. It is annoying. Get rid of it. Please. The agent version we are using is 3.234.0

**Comment by omaraladin** [comment]
I'm facing the same issue on a RHEL 8 behind a proxy

**Comment by omaraladin** [comment]
just pasting my vstsagent .env file here, for people who works behind the proxy. It is always the number 1 suspect of things not working. after I modified to the below, the issue disappeared
```
HTTP_PROXY=http://proxy.company.com:3128
HTTPS_PROXY=http://proxy.company.com:3128
http_proxy=http://proxy.company.com:3128
https_proxy=http://proxy.company.com:3128
```

and I second the comment that encouraged azure team to enhance logging of the vstsAgent!

**Comment by JtMotoX** [comment]
Posting here does not help anything. This is a closed issue and will not be reviewed by the developers. Please open a new issue and provide the link here so users can get directed to the new issue and upvote it.
