### ISSUE TITLE
[BUG]: v3.230.2 not starting jobs | _apis/FeatureFlags/DistributedTask.Agent.UseMaskingPerformanceEnhancements is not authorized

### ISSUE THREAD

**Issue by jensheidrich-acn** [microsoft/azure-pipelines-agent#4562]
### What happened?

Hi,
Installed a new Agent (v.3.230.2) on a new Build Machine (MAC OS Sonoma).
Configured it against our Azure DevOps Server 2020 Update 1.2

Starting an existing build pipeline....process is stuck at the very beginning.

Agent logs showing:
```
ERR  VisualStudioServices] GET request to https://xxx.com/_apis/FeatureFlags/DistributedTask.Agent.UseMaskingPerformanceEnhancements is not authorized. Details: TF400813: The user 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' is not authorized to access this resource.
INFO MessageListener] Sleeping for 13.746 seconds before retrying.
[2023-12-11 14:53:27Z INFO JobDispatcher] Successfully renew job request 894423, job is valid till 11.12.2023 15:03:27
...
```

Potentially introduced here:
https://github.com/microsoft/azure-pipelines-agent/pull/4415

### Versions

Azure Pipeline Agent v3.230.2
Azure DevOps Server 2020 Update 1.2
MAC OS Sonoma

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

Azure DevOps Server (Please specify exact version in the textbox below)

### Azure DevOps Server Version (if applicable)

Azure DevOps Server 2020 Update 1.2

### Relevant log output

```shell
ERR  VisualStudioServices] GET request to https://xxx.com/_apis/FeatureFlags/DistributedTask.Agent.UseMaskingPerformanceEnhancements is not authorized. Details: TF400813: The user 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' is not authorized to access this resource.
INFO MessageListener] Sleeping for 13.746 seconds before retrying.
[2023-12-11 14:53:27Z INFO JobDispatcher] Successfully renew job request 894423, job is valid till 11.12.2023 15:03:27
```

**Comment by DmitriiBobreshev** [comment]
Hi @jensheidrich-acn! Thank you for the feedback. We'll try to fix it in the next release, for now, could you please try [the previous](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v3.230.0) version?

**Comment by DmitriiBobreshev** [comment]
Could you please share us [agent's diagnostic logs](https://learn.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops#agent-diagnostic-logs)? 
If you don't want to share them in the ticket, you could send me it directly on v-bobreshevd@microsoft.com

**Comment by jensheidrich-acn** [comment]
Sent via email.

**Comment by tinylabspace** [comment]
Can confirm that this happens for me also using agent version 3.230.2 with Azure DevOps Server 2022.0.1 Patch 4 and 2022.1 RC1.

**Comment by ismayilov-ismayil** [comment]
@tinylabspace thanks for reporting. Could you please check reconfiguration the agent? 
I mean `config.cmd remove'` then `config.cmd` again

**Comment by kirill-ivlev** [comment]
Hi @jensheidrich-acn, @tinylabspace.
The issue should be resolved in the latest agent (which can be downloaded from [this](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v3.232.1) page).
Could you please confirm that now everything is working as expected?

**Comment by imami777** [comment]
Hello, I just tried deploying version 3.232.1 and I am still getting this error ( ERR  VisualStudioServices] POST request to https://donthackmebro.com/tfs/_apis/CustomerIntelligence/Events is not authorized. Details: TF400813: The user 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' is not authorized to access this resource. )

**Comment by HT-Jens** [comment]
Worked for me to upgrade the PipeLine to version 3.232.1
Have on prem. DevOps server 2022.1

**Comment by jensheidrich-acn** [comment]
> Hi @jensheidrich-acn, @tinylabspace. The issue should be resolved in the latest agent (which can be downloaded from [this](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v3.232.1) page). Could you please confirm that now everything is working as expected?

Yes works fine at our systems!
Thanks for the quick support.

**Comment by Lotti** [comment]
The bug is still present in 3.232.1 agent. Let me know how I can provide details to help you.

**Comment by mkriventsev** [comment]
Can confirm it occurring on Windows agent v.3.232.3.

**Comment by donikatz** [comment]
Issue still exists in 3.236.1 agent on Linux. Downgrading to 3.225.3 resolves it. On-prem ADO Server 2020 w/ latest patches.

**Comment by imami777** [comment]
@donikatz Hello, do you mind if I ask what version of Linux you are using?

**Comment by imami777** [comment]
@donikatz ah interesting, it hadn't occurred to me to try a different Linux distro. I had been operating under the assumption that I could not get V3 agents to work because we're still using version 2020 of Azure DevOps Server,  therefore I was planning on updating to 2022 as soon as possible. However, one of the devs wanted to mess around with his own build agent and was able to get the latest version to work instantly without any problem whatsoever. The only obvious difference between his VM and mine is that he is using Ubuntu 22.04 and I'm still using 20.04 for reasons of compatibility with the v2 agent. I'm going to try installing a v3 agent on a 22.04 VM to see if it works. Incidentally I am starting to wonder if the problem is related in some way to openssl versions, even though the way in which the issue manifests, at least superficially, does not seem to be related.

**Comment by joperator** [comment]
I have the same issue when trying to register an agent:

```
Microsoft.VisualStudio.Services.Common.VssUnauthorizedException: TF400813: Resource not available for anonymous access. Client authentication required.
  at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
  at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
  at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
  at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
  at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
  at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.GetConnectionDataAsync(ConnectOptions connectOptions, Int64 lastChangeId, CancellationToken cancellationToken, Object userState)
  at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.GetConnectionDataAsync(ConnectOptions connectOptions, Int32 lastChangeId, CancellationToken cancellationToken)
  at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.ConnectAsync(ConnectOptions connectOptions, CancellationToken cancellationToken)
  at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.EnsureConnectedAsync(ConnectOptions optionsNeeded, CancellationToken cancellationToken)
  at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.CheckForServerUpdatesAsync(CancellationToken cancellationToken)
  at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.FindServiceDefinitionsAsync(String serviceType, CancellationToken cancellationToken)
  at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.GetResourceLocationsAsync(CancellationToken cancellationToken)
  at Microsoft.VisualStudio.Services.WebApi.VssConnection.GetClientInstanceAsync(Type managedType, Guid serviceIdentifier, CancellationToken cancellationToken, VssHttpRequestSettings settings, DelegatingHandler[] handlers)
  at Microsoft.VisualStudio.Services.WebApi.VssConnection.GetClientServiceImplAsync(Type requestedType, Guid serviceIdentifier, Func`4 getInstanceAsync, CancellationToken cancellationToken)
  at Microsoft.VisualStudio.Services.WebApi.VssConnection.GetClientAsync[T](CancellationToken cancellationToken)
  at Microsoft.VisualStudio.Services.WebApi.TaskExtensions.SyncResult[T](Task`1 task)
  at Microsoft.VisualStudio.Services.WebApi.VssConnection.GetClient[T]()
  at Agent.Listener.Configuration.FeatureFlagProvider.GetFeatureFlagWithCred(IHostContext context, String featureFlagName, ITraceWriter traceWriter, AgentSettings settings, VssCredentials creds, CancellationToken ctk) in src/Agent.Listener/Configuration/FeatureFlagProvider.cs:line 59
```

As the stack trace indicates, the exception is thrown when [vssConnection.GetClient\<FeatureAvailabilityHttpClient\>()](https://github.com/microsoft/azure-pipelines-agent/blob/8d741d220962e458f3da92a0a7f2d5fe35c63825/src/Agent.Listener/Configuration/FeatureFlagProvider.cs#L59) is called. Is there any reason for not moving this line to the following `try` block? I'd guess that this is what @kirill-ivlev was already trying to accomplish with #4568.

**Comment by kirill-ivlev** [comment]
@Lotti @mkriventsev,
Could you please share details about your environment and attach agent diagnostic logs, we will take a look.

Thanks!

**Comment by joperator** [comment]
I've found a workaround by setting the environment variable `STORE_AGENT_KEY_IN_CSP_CONTAINER` to `true` before configuring the agent. I'd guess the handling of the option to store tokens in named containers is inconsistent, resulting in this now being a mandatory requirement.

**Comment by Lotti** [comment]
@kirill-ivlev I'll ask to sysadmin. Meanwhile, I can add that the problem occurred while having VPN problems between Azure and our datacenter.
Solved that problem, the errore never came back.
Btw, we are running agents on Ubuntu 18/22 and RHEL 7/8 machines.

**Comment by anish-george88** [comment]
I am still facing this issue even with the very latest ado agent.

Self-Hosted
Linux x64 Ubuntu 20
No of Parallel jobs - 13
Number of agents - 10 (2 build machines, 5 agents each)
Agent version: 3.242.1 (latest)

Any suggestions?

**Comment by shunkino** [comment]
We also have experienced similar issue discessed here. Diagnostic log shows following message. 
[2024-07-19 08:43:53Z WARN VisualStudioServices] Retrieving an AAD auth token took a long time (99.9020056 seconds) 
[2024-07-19 08:43:53Z WARN VisualStudioServices] GET request to https://dev.azure.com/***/_apis/FeatureFlags/DistributedTask.Agent.UseMaskingPerformanceEnhancements timed out after 100 seconds.

As mentioned in previous posts, I think the cause of this error is the process that tries to check the feature flag DistributedTask.Agent.UseMaskingPerformanceEnhancements, which is implemented [here](https://github.com/microsoft/azure-pipelines-agent/blob/c660a56de1b0844099731fae1f8bdd7c7d9b6161/src/Agent.Listener/JobDispatcher.cs#L401 ). 
In this implementation, featureFlagProvider.GetFeatureFlagAsync is executed before launching the worker process, so if an unhandled exception occurs here, the worker process will not start and the job execution will fail. featureFlagProvider.GetFeatureFlagAsync is implemented in [this line](https://github.com/microsoft/azure-pipelines-agent/blob/c660a56de1b0844099731fae1f8bdd7c7d9b6161/src/Agent.Listener/Configuration/FeatureFlagProvider.cs#L62C30-L62C62).  I think the error excerpted above occurred because the communication with the Azure DevOps endpoint that manages the feature flag exceeded the 100-second timeout limit in GetFeatureFlagByNameAsync, which is called on line 62. In this implementation, exceptions wrapped in VssUnauthorizedException are caught, but it seems like in the case of a timeout, an exception that is not wrapped in VssUnauthorizedException occurs and causes unexpected behavior. 

It may be possible to suppress such errors by considering improvements in the scope of exception handling.

**Comment by DmitriiBobreshev** [comment]
Hi @shunkino, the [vssconnection ](https://github.com/microsoft/azure-pipelines-agent/blob/master/src/Agent.Sdk/Util/VssUtil.cs#L93) which is used in the [featureFlagProvider](https://github.com/microsoft/azure-pipelines-agent/blob/master/src/Agent.Listener/Configuration/FeatureFlagProvider.cs#L58) allow you [to control](https://github.com/microsoft/azure-pipelines-agent/blob/master/src/Agent.Sdk/Util/VssUtil.cs#L109) the timeout(100ms by default) via env variable [VSTS_HTTP_TIMEOUT](https://github.com/microsoft/azure-pipelines-agent/blob/master/src/Agent.Sdk/Knob/AgentKnobs.cs#L307), unfortunately, this knob could not be set via pipeline, but if you're able to set it before the agent is started, it might be the option for you. We'll try to implement a fix in next iterations

**Comment by shunkino** [comment]
Hello @DmitriiBobreshev, thank you for letting me know the potential workaround. This issue occurred only once so I believe it was transient issue, but I will keep that in mind for future use. Hope you can fix the root cause in the future.

**Comment by kirill-ivlev** [comment]
Closing since fix merged to the master.

**Comment by shunkino** [comment]
Great thank you!
